### PR TITLE
Remove sftp from production images

### LINKED ISSUE #120: Remove sftp service from production compose file
The sftp service was added to do a bit of testing - it shouldn't be a part of the "production" docker compose file.
Furthermore, I suggest to utilize it more for testing if it is to be kept in the "development" docker compose file.

### PR DESCRIPTION
**Pull request by CasperWA**
# Description:

Remove the SFTP service from the production Docker Compose file, as well as the production simili file used in CI tests.

Update the README accordingly, and also add instructions for starting AllegroGraph when not using Docker Compose.

Closes #120 

## Type of change:

- [ ] Bug fix.
- [ ] New feature.
- [x] Documentation update.

## Checklist for the reviewer:

This checklist should be used as a help for the reviewer.

- [ ] Is the change limited to one issue?
- [ ] Does this PR close the issue?
- [ ] Is the code easy to read and understand?
- [ ] Do all new feature have an accompanying new test?
- [ ] Has the documentation been updated as necessary?

### CODE REVIEW

**Comment by quaat** [comment]
We might need the SFTP server until we have a proper object store.

**Comment by CasperWA** [comment]
You want to use it as the results backend for data retrieval? In any case, this "only" removes it from all production images and stuff. Still there for the development build targets and setups.

**Review by quaat — APPROVED** [review]
Follow up task is to make a generic triplestore interface. sftp should also be replaced with MinIO

**Comment by CasperWA** [comment]
> Follow up task is to make a generic triplestore interface. sftp should also be replaced with MinIO

I have created issue #283 from this comment 👍

**Pull request merged**
