### PR TITLE
Trj/75 add a triplestore and sample endpoint

### PR DESCRIPTION
**Pull request by Treesarj**
- add a triple store to the docker-compose 
- sample query endpoint

### CODE REVIEW

**Comment by Treesarj** [comment]
Need to update the oteapi-core version in requirements for the tests to pass

**Review by CasperWA — APPROVED** [review]
Add the AllegroGraph user details as configuration/settings parameters in the application.
Then they can be accessed by the application as well - if that's necessary?
If it's not necessary, then never mind :)

**Comment by Treesarj** [comment]
> Add the AllegroGraph user details as configuration/settings parameters in the application. Then they can be accessed by the application as well - if that's necessary? If it's not necessary, then never mind :)

The Triple store config requires the user credentials, so I guess it's not necessary.

**Comment by CasperWA** [comment]
> > Add the AllegroGraph user details as configuration/settings parameters in the application. Then they can be accessed by the application as well - if that's necessary? If it's not necessary, then never mind :)
> 
> The Triple store config requires the user credentials, so I guess it's not necessary.

Okay. Just for the record, what I meant by application settings was this class: https://github.com/EMMC-ASBL/oteapi-services/blob/master/app/main.py#L26:L37

**Review by kriwiik — APPROVED** [review]

**Pull request merged**
